### PR TITLE
Advanced Adventuring and Generated Structures

### LINKED ISSUE #35: Advanced adventuring, specifically structures
### Overworld

- [x] Ruined nether portals @jamespeilunli 
- [x] Mineshaft @jamespeilunli 
- [x] Dungeons @dealingwith 
- [x] Desert pyramids @jamespeilunli 
- [x] Jungle temples @jamespeilunli 
- [x] Shipwrecks @dealingwith 
- [x] Buried treasure @jamespeilunli  
- [x] Ocean ruins (what are their real name?) @dealingwith 
- [x] Ocean monument (keep it simple) @dealingwith 
- [x] Igloos @jamespeilunli 
- [x] Pillager outpost @jamespeilunli
- [x] Woodland mansion @dealingwith 
- [x] Stronghold @dealingwith 

### Nether

- [x] Nether fortresses @dealingwith 
- [x] Bastion remnants @jamespeilunli 

Skip End structures for now.

### PR DESCRIPTION
**Pull request by jamespeilunli**
closes #35

### CODE REVIEW

**Comment by jamespeilunli** [comment]
Add or remove the generated structures we are covering if you want.

**Comment by dealingwith** [comment]
I just merged #37 and rebased this branch. Then I force-pushed to GitHub. If everything looks good here, you will need to reset your local branch to this remote version by running `git fetch` then `git reset --hard origin/main`.

**Comment by dealingwith** [comment]
I think this should just be _Section 11_. What do you think? If so, then we can just rename `generated_structures.md` to `section_11.md` and we don't have to rename any existing sections.

**Comment by jamespeilunli** [comment]
I just realized that the section numbers in the headers of sections after 6 are off by one (e.g. [Skin Design and Autosmelters](https://github.com/MinecraftU/mcu-curriculum/blob/main/level_2/section_10.md)). I think we should update this and force-push again.

**Comment by dealingwith** [comment]
We won't have to force-push, I don't think

**Pull request merged**
