### PR TITLE
Villager trading

### LINKED ISSUE #33: Villager trading

### PR DESCRIPTION
**Pull request by dealingwith**
closes #33

### CODE REVIEW

**Comment by dealingwith** [comment]
https://minecraft.fandom.com/wiki/Villager

**Comment by jamespeilunli** [comment]
I added a few potential trading images you might want to use (feel free to make your own though). I also added fletcher images, because I think we should note that the fletcher is a good source of emeralds (traded from sticks).

**Comment by dealingwith** [comment]
Thank you @jamespeilunli!

**Comment by dealingwith** [comment]
@jamespeilunli what else do you think is needed here? I think we decided this PR needs to go in first so you can slot your module in wherever it needs to go. (Because this one already renames a bunch of modules.)

**Comment by jamespeilunli** [comment]
I think we should give a brief description of what villagers are, where they are found, and their behavior (e.g. job block behavior; see wiki), perhaps at the very start in a single paragraph (we can put types of villagers under a `##`). I'll try to work on this as soon as I can.

**Review by jamespeilunli — COMMENTED** [review]
Looks good, but I want you to review my changes.

**Pull request merged**
