### PR TITLE
new caption style

### LINKED ISSUE #29: Fixup image captions

### PR DESCRIPTION
**Pull request by dealingwith**
closes #29 

let's see how these look. I'm off to look for a legit Github markdown preview tool since VSCode's wasn't exactly the same...

### CODE REVIEW

**Comment by dealingwith** [comment]
Ok, according to this preview tool I downloaded, using "GitHub2" (I don't know what the difference between "GitHub" and "GitHub2" is), it looks like it might end up being ok. It just uses a table with an HR.

Screen Shot 2022-04-17 at 5 09 07 PM

**Review by jamespeilunli — CHANGES_REQUESTED** [review]
The captions look great! Just one correction - "bookshelf table" should just be "bookshelf".

**Comment by dealingwith** [comment]
@jamespeilunli fixed!

**Comment by jamespeilunli** [comment]
The label for the image is still the same; you should probably fix that too.

**Comment by dealingwith** [comment]
@jamespeilunli good catch. Fixed!

**Review by jamespeilunli — APPROVED** [review]
Great!

**Pull request merged**
